//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to უკაცრავად დაფიქსირდა შეცდომა.
        /// </summary>
        public static string TextAbort {
            get {
                return ResourceManager.GetString("TextAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქალი.
        /// </summary>
        public static string TextFemale {
            get {
                return ResourceManager.GetString("TextFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კაცი.
        /// </summary>
        public static string TextMale {
            get {
                return ResourceManager.GetString("TextMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ოპერაცია დასრულდა წარმატებით.
        /// </summary>
        public static string TextSuccess {
            get {
                return ResourceManager.GetString("TextSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ველის შევსება სავალდებულოა.
        /// </summary>
        public static string ValidationFieldIsRequired {
            get {
                return ResourceManager.GetString("ValidationFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პირადი ნომერი უნდა იყოს 11 ნიშნა.
        /// </summary>
        public static string ValidationPersonalNumberMustBeElevenDigits {
            get {
                return ResourceManager.GetString("ValidationPersonalNumberMustBeElevenDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სტუდენტი ასეთი პირადი ნომრით უკვე არსებობს.
        /// </summary>
        public static string ValidationPersonalNumberMustBeUnique {
            get {
                return ResourceManager.GetString("ValidationPersonalNumberMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სტუდენტი უნდა იყოს 16 წელზე ზევით.
        /// </summary>
        public static string ValidationStudentMustBeMoreThenSixteenYearsOld {
            get {
                return ResourceManager.GetString("ValidationStudentMustBeMoreThenSixteenYearsOld", resourceCulture);
            }
        }
    }
}
